const todos = [
  { id: 1, title: 'New todo', state: false },
  { id: 2, title: 'Meeting my friend', state: false },
  { id: 3, title: 'Drink coffee', state: true },
  { id: 4, title: 'New todo', state: false },
  { id: 5, title: 'Meeting my friend', state: false },
  { id: 6, title: 'Drink coffee', state: false },
  { id: 7, title: 'Drink coffee', state: false },
  { id: 8, title: 'Read a book', state: false },
  { id: 9, title: 'Go for a walk', state: true },
  { id: 10, title: 'Workout', state: false },
  { id: 11, title: 'Cook dinner', state: false },
  { id: 12, title: 'Call mom', state: true },
  { id: 13, title: 'New todo', state: false },
  { id: 14, title: 'Meeting my friend', state: false },
  { id: 15, title: 'Drink coffee', state: false },
  { id: 16, title: 'New todo', state: false },
  { id: 17, title: 'Meeting my friend', state: false },
  { id: 18, title: 'Drink coffee', state: false },
  { id: 19, title: 'Read a book', state: false },
  { id: 20, title: 'Go for a walk', state: false },
  { id: 21, title: 'Workout', state: false },
  { id: 22, title: 'Cook dinner', state: false },
  { id: 23, title: 'Call mom', state: true },
  { id: 24, title: 'New todo', state: false },
  { id: 25, title: 'Meeting my friend', state: false },
  { id: 26, title: 'Drink coffee', state: true },
  { id: 27, title: 'New todo', state: false },
  { id: 28, title: 'Meeting my friend', state: false },
  { id: 29, title: 'Drink coffee', state: false },
  { id: 30, title: 'Read a book', state: false },
  { id: 31, title: 'Go for a walk', state: false },
  { id: 32, title: 'Workout', state: false },
  { id: 33, title: 'Cook dinner', state: true },
  { id: 34, title: 'Call mom', state: false },
  { id: 35, title: 'New todo', state: false },
  { id: 36, title: 'Meeting my friend', state: false },
  { id: 37, title: 'Drink coffee', state: false },
  { id: 38, title: 'New todo', state: false },
  { id: 39, title: 'Meeting my friend', state: true },
  { id: 40, title: 'Drink coffee', state: false },
  { id: 41, title: 'Read a book', state: false },
  { id: 42, title: 'Go for a walk', state: false },
  { id: 43, title: 'Workout', state: false },
  { id: 44, title: 'Cook dinner', state: true },
  { id: 45, title: 'Call mom', state: false },
  { id: 46, title: 'New todo', state: false },
  { id: 47, title: 'Meeting my friend', state: false },
  { id: 48, title: 'Drink coffee', state: false },
  { id: 49, title: 'New todo', state: false },
  { id: 50, title: 'Meeting my friend', state: false },
  { id: 51, title: 'Drink coffee', state: false },
  { id: 52, title: 'Read a book', state: true },
  { id: 53, title: 'Go for a walk', state: false },
  { id: 54, title: 'Workout', state: false },
  { id: 55, title: 'Cook dinner', state: false },
  { id: 56, title: 'Call mom', state: true },
  { id: 57, title: 'New todo', state: false },
  { id: 58, title: 'Meeting my friend', state: false },
  { id: 59, title: 'Drink coffee', state: false },
  { id: 60, title: 'New todo', state: false },
  { id: 61, title: 'Meeting my friend', state: true },
  { id: 62, title: 'Drink coffee', state: false },
  { id: 63, title: 'Read a book', state: false },
  { id: 64, title: 'Go for a walk', state: false },
  { id: 65, title: 'Workout', state: false },
  { id: 66, title: 'Cook dinner', state: true },
  { id: 67, title: 'Call mom', state: false },
  { id: 68, title: 'New todo', state: false },
  { id: 69, title: 'Meeting my friend', state: false },
  { id: 70, title: 'Drink coffee', state: false },
  { id: 71, title: 'New todo', state: false },
  { id: 72, title: 'Meeting my friend', state: true },
  { id: 73, title: 'Drink coffee', state: false },
  { id: 74, title: 'Read a book', state: false },
  { id: 75, title: 'Go for a walk', state: false },
  { id: 76, title: 'Workout', state: false },
  { id: 77, title: 'Cook dinner', state: true },
  { id: 78, title: 'Call mom', state: false },
  { id: 79, title: 'New todo', state: false },
  { id: 80, title: 'Meeting my friend', state: false },
  { id: 81, title: 'Drink coffee', state: false },
  { id: 82, title: 'New todo', state: false },
  { id: 83, title: 'Meeting my friend', state: false },
  { id: 84, title: 'Drink coffee', state: true },
  { id: 85, title: 'Read a book', state: false },
  { id: 86, title: 'Go for a walk', state: false },
  { id: 87, title: 'Workout', state: false },
  { id: 88, title: 'Cook dinner', state: false },
  { id: 89, title: 'Call mom', state: true },
  { id: 90, title: 'New todo', state: false },
  { id: 91, title: 'Meeting my friend', state: false },
  { id: 92, title: 'Drink coffee', state: false },
  { id: 93, title: 'New todo', state: false },
  { id: 94, title: 'Meeting my friend', state: true },
  { id: 95, title: 'Drink coffee', state: false },
  { id: 96, title: 'Read a book', state: false },
  { id: 97, title: 'Go for a walk', state: false },
  { id: 98, title: 'Workout', state: false },
  { id: 99, title: 'Cook dinner', state: true },
  { id: 100, title: 'Call mom', state: false },
];
export default todos;
